name: Deploy via Jekyll on GitHub  pages

on:
  push:
    branches:
      - source
  schedule:
    - cron:  '0 0 * * *'

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - uses: iranzo/gh-pages-jekyll-action@d27999d323a83e1989f4b62f5176f0b4736066d3 # 1.0.2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SOURCE_FOLDER: ./
        GH_PAGES_BRANCH: master
